### ISSUE TITLE
Library naming conflicts

### ISSUE THREAD

**Issue by Tyler-H** [CopernicaMarketingSoftware/PHP-JS#3]
Just want to bring this to your attention that there already exists a PHP.js library out there: http://phpjs.org/ (existing some years before this one), and while I'm not necessarily expecting you to change the name of this, I do want to point out that it's a potential [source of great confusion](http://meta.stackoverflow.com/questions/319026/do-we-need-php-js-tag-there-is-a-phpjs-tag-but-it-is-different-from-php-js) (that link will require being logged in with a Stack Overflow account w/ at least 5 reputation)

**Comment by EmielBruijntjes** [comment]
Thanks for letting us know. PHP-JS was indeed maybe not the best possible or most unique name for this library. We just made a bridge between PHP and JS because we needed it ourselves. We put it on Github in case someone else ever needed it - we never thought about marketing or good names or anything.

To our surprise the last couple of weeks this project seems to be picked up by others than just ourselves.
