### ISSUE TITLE
How does this differ from the v8js php ext

### ISSUE THREAD

**Issue by christiaan** [CopernicaMarketingSoftware/PHP-JS#4]
https://github.com/phpv8/v8js has been around for quite a while already.

How is this extension any different?

**Comment by ghost** [comment]
Well, PHP-JS works on both PHP 5.3+ and PHP 7.0+ where v8js only works on PHP 7.0+. PHP-JS integrates more, exceptions can be passed on from both sides to the other transparantly instead of using a 'getPendingException' function. We support assigning variables to the global javascript scope.

There are many differences I assume, I am not familiar with the other project but this is what I see at first glance.
